FROM node:20-bullseye-slim

WORKDIR /workspace/blog_client

RUN mkdir -p /workspace/blog_client/node_modules

# 依存関係をインストール
COPY blog_client/package.json blog_client/package-lock* ./

RUN npm install

RUN chown -R node:node ./
USER node

# Next.jsによってテレメトリデータを収集するのを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# 注意: ポートのマッピングはdocker-composeで行うため、設定しない

CMD ["node", "run", "dev"]